server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #mybatis配置文件所在路径
  type-aliases-package: com.wuzx.pojo                             #所有pojo别名类所在的包
  mapper-locations:  classpath:mybatis/mapper/**/*.xml            #mapper映射文件

spring:
  application:
    name: springcloud-dept                                        #服务名称（对外暴露的微服务名字）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  #数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                    #mysql驱动包
    url: jdbc:mysql://120.78.81.89:3306/springcloud               #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                                 #数据库连接池的最先维持连接数
      initial-size: 5                                             #初始化连接数
      max-total: 5                                                #最大连接数
      max-wait-millis: 200                                        #等待连接获取的最大超时时间


eureka:
  client: #客户端注册进Eureka服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-dept-hystrix-8001 #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示IP地址



info:
  app.name: springcloud
  company.name: www.wuzx.club:8080
  build.artifactId: $project.artifactId$
  build.version: $project.version$
